//! Build script for Zenless Setup.
//!
//! 1. **Payload embedding.** Every file of [`payload_format::FILES`] found in
//!    `payload/` (or `$ZENLESS_PAYLOAD_DIR`) is compressed into `OUT_DIR` and a
//!    `payload.rs` is generated with its size and SHA-256. Missing files become
//!    `data: None`, meaning "download at install time" (online installer).
//! 2. **Windows resources.** Embeds the icon, version info and the `asInvoker`
//!    manifest. Uses `zig rc` when zig is on PATH (works for both the GNU and
//!    MSVC toolchains), otherwise falls back to `embed-resource` (rc.exe /
//!    windres). The manifest matters: without it Windows' installer detection
//!    would force a UAC prompt on an exe named "Setup".

use std::{env, fs, path::PathBuf, process::Command};

#[path = "src/payload_format.rs"]
mod payload_format;

const PRODUCT: &str = "Zenless Suite";
const DESCRIPTION: &str = "Zenless Suite Setup";
const EXE_NAME: &str = "ZenlessSetup.exe";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/payload_format.rs");
    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=assets/app.manifest");

    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    embed_payload(&root, &out);

    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        embed_resources(&root, &out);
    }
}

fn embed_payload(root: &std::path::Path, out: &std::path::Path) {
    println!("cargo:rerun-if-env-changed=ZENLESS_PAYLOAD_DIR");
    let dir = env::var_os("ZENLESS_PAYLOAD_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("payload"));
    // A directory is scanned recursively by cargo, so adding, replacing or
    // removing a payload file re-runs this script.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut code = String::from(
        "// @generated by build.rs - embedded payload table. Do not edit.\n",
    );
    for (ident, file) in payload_format::FILES {
        let data = fs::read(dir.join(file)).ok().filter(|d| !d.is_empty());
        let Some(data) = data else {
            code += &payload_format::entry_source(ident, file, None, 0, None);
            continue;
        };
        let sha = payload_format::sha256_hex(&data);
        let blob = format!("{file}.deflate");
        let blob_path = out.join(&blob);
        let stamp_path = out.join(format!("{file}.sha256"));
        // Re-use the previous compression when the source did not change.
        let fresh = fs::read_to_string(&stamp_path).is_ok_and(|s| s.trim() == sha) && blob_path.exists();
        if !fresh {
            fs::write(&blob_path, payload_format::encode(&data)).expect("write compressed payload");
            fs::write(&stamp_path, &sha).expect("write payload stamp");
        }
        code += &payload_format::entry_source(ident, file, Some(&blob), data.len() as u64, Some(&sha));
    }
    fs::write(out.join("payload.rs"), code).expect("write payload.rs");
}

fn embed_resources(root: &std::path::Path, out: &std::path::Path) {
    let esc = |p: PathBuf| p.display().to_string().replace('\\', "\\\\");
    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let mut parts: Vec<u16> = version.split(['.', '-']).filter_map(|s| s.parse().ok()).collect();
    parts.resize(4, 0);
    let bin_version = parts.iter().map(u16::to_string).collect::<Vec<_>>().join(",");

    let rc = format!(
        r#"#pragma code_page(65001)
1 ICON "{icon}"
1 24 "{manifest}"
1 VERSIONINFO
FILEVERSION {bin_version}
PRODUCTVERSION {bin_version}
FILEOS 0x40004
FILETYPE 0x1
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904B0"
    BEGIN
      VALUE "CompanyName", "Zenless"
      VALUE "FileDescription", "{DESCRIPTION}"
      VALUE "FileVersion", "{version}"
      VALUE "InternalName", "{EXE_NAME}"
      VALUE "LegalCopyright", "MIT License"
      VALUE "OriginalFilename", "{EXE_NAME}"
      VALUE "ProductName", "{PRODUCT}"
      VALUE "ProductVersion", "{version}"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 1200
  END
END
"#,
        icon = esc(root.join("assets").join("icon.ico")),
        manifest = esc(root.join("assets").join("app.manifest")),
    );
    let rc_path = out.join("app.rc");
    fs::write(&rc_path, rc).expect("write app.rc");

    let obj = out.join("app-resources.o");
    let zig_ok = Command::new("zig")
        .arg("rc")
        .arg("/:output-format")
        .arg("coff")
        .arg("/:target")
        .arg(env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "x86_64".into()))
        .arg(&rc_path)
        .arg(&obj)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if zig_ok {
        println!("cargo:rustc-link-arg-bins={}", obj.display());
    } else {
        let _ = embed_resource::compile(&rc_path, embed_resource::NONE);
    }
}
